# Generated by Django 2.1.1 on 2018-09-30 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=31, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='이름')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='핸드폰 번호')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='이메일')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='보유금')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='설명')),
                ('education', models.TextField(blank=True, verbose_name='학력')),
                ('experience', models.TextField(blank=True, verbose_name='경력')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('profile_image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': '상담사',
                'verbose_name_plural': '상담사',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(verbose_name='예약 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='예약 신청 일자')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 취소 일자')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='sinabro.Consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('status', models.CharField(choices=[('R', 'request'), ('D', 'Done'), ('C', 'Cancel')], default='R', max_length=2, verbose_name='결제 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 내역 생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='결제 취소 일자')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='sinabro.ConsultationRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 내역',
                'verbose_name_plural': '결제 내역',
            },
        ),
    ]
