# Generated by Django 2.1.1 on 2018-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinabro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='상담 신청 사유'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='region',
            field=models.CharField(choices=[('Ganam', '강남 본점'), ('Busan', '부산 센터'), ('Ulsan', '울산 센터'), ('Changwon', '창원 센터'), ('Gangdong', '강동 센터')], default='Ganam', max_length=100, verbose_name='지역'),
        ),
    ]
