# Generated by Django 2.1.1 on 2018-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinabro', '0002_auto_20180930_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(default='R', max_length=20, verbose_name='상태'),
        ),
    ]
