# Generated by Django 2.1.1 on 2018-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinabro', '0003_consultationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('요청 완료', '요청 완료'), ('결제 완료', '결제 완료 '), ('상담 취소', '상담 취소'), ('상담 완료', '상담 완료')], default='요청 완료', max_length=20, verbose_name='상태'),
        ),
    ]
