# Generated by Django 2.1.1 on 2018-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinabro', '0004_auto_20180930_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('D', '결제 완료'), ('C', '결제 취소')], default='D', max_length=2, verbose_name='결제 상태'),
        ),
    ]
